### ISSUE TITLE
IB Support?

### ISSUE THREAD

**Issue by Sweeper777** [andgotravel/NGORoundedButton#5]
At the moment, IB does not seem to be supported. Can you add support for that so I can create rounded buttons in the storyboard and set its color, image etc.?

**Comment by Zhukn1** [comment]
Hi @Sweeper777, 

Adding IB support wasn't something from the "must have features" list. I'd gladly accept your pull request, though 😉

**Comment by Sweeper777** [comment]
Okay, I see... I can't write Objective-C though. I guess I'll close this for now.
